name: 'push json to java repo'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: '8.0.242' # The JDK version to make available on the path.
      - name: Setup Maven
        uses: stCarolas/setup-maven@v1
      - name: Checkout
        uses: actions/checkout@master
      - name: assembly
        run: mvn assembly:assembly
      - name: change file name
        run: |
          cd /tmp
          mkdir output
          cd /home/runner/work/json-schema-to-pojo/json-schema-to-pojo/schema/target
          mv json-schema-to-pojo-1.0-SNAPSHOT-jar-with-dependencies.jar /tmp/output/jsonschema2pojo.jar
      - name: Push to action branch
        uses: wu-yu-xuan/deploy-github-pages@action
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          commit_message: ${{ github.event.head_commit.message }}
          publish_branch: action
          source_dir: /tmp/output


