name: 'push json to java repo'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: moving
        run: |
          cd /tmp
          mkdir workdir
          cd workdir
          mkdir docker
          cd docker
          mkdir output
      - run: chmod +x entrypoint.sh
      - uses: DominikYang/json-schema-to-pojo@master
        with:
          srcPath: src/main/resources/path
          outPath: /tmp/workdir/docker/output
          packageNameForVO: com.example.test.vo
          packageNameForDTO: com.example.test.dto
      - name: check if exist
        run: |
          cd /tmp/workdir/docker/output/com
          ls -la

